name: Deployment Android

on:
  workflow_call:
    inputs:
      fastlane-command:
        required: true
        type: string

env:
  FLUTTER_CHANNEL: 'stable'
  FLUTTER_VERSION: '3.13.8'
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_VERSION: '17'
  RUBY_VERSION: '3'

jobs:
  deploy-fastlane-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}
          cache: 'gradle'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
          working-directory: android

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{ env.FLUTTER_CHANNEL }}
          flutter-version: ${{ env.FLUTTER_VERSION }}
          architecture: x64
          cache: true

      - name: Doctor Flutter
        run: |
          dart --version
          flutter --version
          flutter doctor -v

      - name: Download Pubspec.yaml
        uses: actions/download-artifact@v3
        with:
          name: pubspec-${{ github.sha }}

      - name: Setup Firebase Credential
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS_BASE64" | base64 --decode > android/firebase-google-service.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_BASE64 }}

      - name: Setup Android Dependencies
        run: |
          echo "$ANDROID_KEYSTORE_BASE64" | base64 --decode > android/key.jks
          echo "$ANDROID_KEY_PROPERTIES" > android/key.properties
        env:
          ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES }}

      - name: Fastlane Android
        uses: maierj/fastlane-action@v2.3.0
        with:
          subdirectory: 'android'
          bundle-install-path: './vendor/bundle'
          lane: ${{ inputs.fastlane-command }}
        env:
          CI_BRANCH: ${{ github.ref_name }}
          CI_SHA: ${{ github.sha }}
          GOOGLE_APPLICATION_CREDENTIALS: './firebase-google-service.json'
          PLAY_STORE_JSON_KEY_DATA: ${{ secrets.PLAY_STORE_JSON_KEY_DATA }}
          FASTLANE_SKIP_UPDATE_CHECK: true
          FASTLANE_HIDE_CHANGELOG: true
